[package]
name = "media"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
pubsub = { path = "../pubsub", version = "0.1.0" }
sdp = { version = "0.6.2" }
